/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package DEVSJAVALab;

import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

/**
 * @author David
 */
public class DNGlycolysis extends ViewableDigraph {

    public DNGlycolysis() {
        this("Glycolysis");
    }

    public DNGlycolysis(String nm) {
        super(nm);
        DNGlycolysisConstructor();
    }

    public void DNGlycolysisConstructor() {
        this.addOutport("out1");
        this.addInport("in1");

        ViewableDigraph dNReaction = new DNReaction("Reaction");
        ViewableDigraph dNSubstrate = new DNSubstrate("Substrate");
        ViewableDigraph dNEnzyme = new DNEnzyme("Enzyme");
        ViewableAtomic dNProduct = new DNProduct("Product");
        ViewableAtomic dNGlucoseGenerator = new DNGlucoseGenerator();


        add(dNReaction);
        add(dNSubstrate);
        add(dNEnzyme);
        add(dNProduct);
        add(dNGlucoseGenerator);

        addCoupling(dNReaction, "out2", dNProduct, "in1");
        addCoupling(dNReaction, "out1", dNEnzyme, "in1");
        addCoupling(dNSubstrate, "out1", dNReaction, "in1");
        addCoupling(dNEnzyme, "out1", dNReaction, "in2");
        addCoupling(dNProduct, "out1", dNSubstrate, "in2");
        addCoupling(dNGlucoseGenerator, "out1", dNSubstrate, "in2");

    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView() {
        preferredSize = new Dimension(1172, 578);
        if ((ViewableComponent) withName("Product") != null)
            ((ViewableComponent) withName("Product")).setPreferredLocation(new Point(814, 414));
        if ((ViewableComponent) withName("Substrate") != null)
            ((ViewableComponent) withName("Substrate")).setPreferredLocation(new Point(50, 50));
        if ((ViewableComponent) withName("Reactino") != null)
            ((ViewableComponent) withName("Reactino")).setPreferredLocation(new Point(148, 211));
        if ((ViewableComponent) withName("GlucoseGenerator") != null)
            ((ViewableComponent) withName("GlucoseGenerator")).setPreferredLocation(new Point(-12, 335));
        if ((ViewableComponent) withName("Enzyme") != null)
            ((ViewableComponent) withName("Enzyme")).setPreferredLocation(new Point(50, 50));
    }
}
