package DEVSJAVALab;

import java.awt.Dimension;
import java.awt.Point;
import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

/**
 * Created with IntelliJ IDEA.
 * User: nick
 * Date: 4/17/14
 * Time: 10:56 AM
 * To change this template use File | Settings | File Templates.
 */
public class DNSubstrate extends ViewableDigraph {

    
    public DNSubstrate(){
        this("Substrate");
    }

    public DNSubstrate(String nm){
        super(nm);
        DNSubstrateConstructor();
    }
    
    public void DNSubstrateConstructor() {
        this.addOutport("out");
        this.addInport("in1-Product");
        this.addInport("in1-Glucose");
        
        ViewableAtomic dNProduct = new DNProductReusable("Product",7);
        ViewableAtomic dNGlucose = new DNGlucose("Glucose");
        ViewableAtomic dNCoSubstrate = new DNCoSubstrate("DNCoSubstrate");

        add(dNProduct);
        add(dNGlucose);
        add(dNCoSubstrate);

        //addCoubling(this,"in1-Product", dNGlucose, "in1");
        addCoupling(dNProduct,"out",dNCoSubstrate,"in2");
        addCoupling(dNGlucose,"out",dNCoSubstrate,"in1");
        //addCoupling(dNCoSubstrate,"out",DNSubstrate,"in");

    }
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(395, 259);
        if((ViewableComponent)withName("DNCoSubstrate")!=null)
             ((ViewableComponent)withName("DNCoSubstrate")).setPreferredLocation(new Point(259, 118));
        if((ViewableComponent)withName("Glucose")!=null)
             ((ViewableComponent)withName("Glucose")).setPreferredLocation(new Point(77, 53));
        if((ViewableComponent)withName("Product")!=null)
             ((ViewableComponent)withName("Product")).setPreferredLocation(new Point(83, 183));
    }
}
