package DEVSJAVALab;

import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

/**
 * Created with IntelliJ IDEA.
 * User: nick
 * Date: 4/17/14
 * Time: 10:56 AM
 * To change this template use File | Settings | File Templates.
 */
public class DNSubstrate extends ViewableDigraph {


    public DNSubstrate() {
        this("Substrate");
    }

    public DNSubstrate(String nm) {
        super(nm);
        DNSubstrateConstructor();
    }

    public void DNSubstrateConstructor() {
        this.addOutport("out1");
        this.addInport("in1");
        this.addInport("in2");

        ViewableAtomic dNProduct = new DNProductReusable("Product", 7);
        ViewableAtomic dNGlucose = new DNGlucose("Glucose");
        ViewableAtomic dNCoSubstrate = new DNCoSubstrate("DNCoSubstrate");

        add(dNProduct);
        add(dNGlucose);
        add(dNCoSubstrate);

        addCoupling(this, "in1", dNProduct, "in1");
        addCoupling(this, "in2", dNGlucose, "in1");
        addCoupling(dNGlucose, "out1", dNCoSubstrate, "in1");
        addCoupling(dNProduct, "out1", dNCoSubstrate, "in2");
        addCoupling(dNCoSubstrate,"out1", this,"out1");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(528, 304);
        if((ViewableComponent)withName("Glucose")!=null)
             ((ViewableComponent)withName("Glucose")).setPreferredLocation(new Point(54, 78));
        if((ViewableComponent)withName("DNCoSubstrate")!=null)
             ((ViewableComponent)withName("DNCoSubstrate")).setPreferredLocation(new Point(181, 134));
        if((ViewableComponent)withName("Product")!=null)
             ((ViewableComponent)withName("Product")).setPreferredLocation(new Point(83, 183));
    }
}
