package DEVSGlycolysis.coupled;

import DEVSGlycolysis.atomic.Fixing;
import DEVSGlycolysis.atomic.Release;
import DEVSGlycolysis.atomic.Transformation;
import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

/**
 * Created with IntelliJ IDEA.
 * User: nick
 * Date: 4/17/14
 * Time: 10:58 AM
 * To change this template use File | Settings | File Templates.
 */
public class Reaction extends ViewableDigraph {

    public Reaction() {
        this("Reaction");
    }

    public Reaction(String nm) {
        super(nm);
        DNReactionConstructor();
    }

    public void DNReactionConstructor() {
        this.addOutport("out1");
        this.addOutport("out2");

        this.addInport("in1");
        this.addInport("in2");

        ViewableAtomic dNFixing = new Fixing("Fixing", 20);
        ViewableAtomic dNTransformation = new Transformation("Transformation");
        ViewableAtomic dNRelease = new Release("Release");

        add(dNFixing);
        add(dNTransformation);
        add(dNRelease);

        addCoupling(this, "in1", dNFixing, Fixing.inPort1);
        addCoupling(this, "in2", dNFixing, Fixing.inPort2);
        addCoupling(dNFixing, Fixing.outPort1, dNTransformation, "in1");
        addCoupling(dNTransformation, "out1", dNRelease, "in1");
        addCoupling(dNRelease, "out1", this, "out1");
        addCoupling(dNFixing, Fixing.outPort2, this, "out2");

    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(633, 196);
        if((ViewableComponent)withName("Fixing")!=null)
             ((ViewableComponent)withName("Fixing")).setPreferredLocation(new Point(-11, 41));
        if((ViewableComponent)withName("Release")!=null)
             ((ViewableComponent)withName("Release")).setPreferredLocation(new Point(367, 30));
        if((ViewableComponent)withName("Transformation")!=null)
             ((ViewableComponent)withName("Transformation")).setPreferredLocation(new Point(164, 32));
    }
}

