package DEVSGlycolysis.coupled;

import DEVSGlycolysis.atomic.CoSubstrate;
import DEVSGlycolysis.atomic.Glucose;
import DEVSGlycolysis.atomic.ProductReusable;
import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

/**
 * Created with IntelliJ IDEA.
 * User: nick
 * Date: 4/17/14
 * Time: 10:56 AM
 * To change this template use File | Settings | File Templates.
 */
public class Substrate extends ViewableDigraph {


    public Substrate() {
        this("Substrate");
    }

    public Substrate(String nm) {
        super(nm);
        DNSubstrateConstructor();
    }

    public void DNSubstrateConstructor() {
        this.addOutport("out1");
        this.addInport("in1");
        this.addInport("in2");

        ViewableAtomic dNProduct = new ProductReusable("Product", 7);
        ViewableAtomic dNGlucose = new Glucose("Glucose");
        ViewableAtomic dNCoSubstrate = new CoSubstrate("CoSubstrate");

        add(dNProduct);
        add(dNGlucose);
        add(dNCoSubstrate);

        addCoupling(this, "in1", dNProduct, "in1");
        addCoupling(this, "in2", dNGlucose, "in1");
        addCoupling(dNGlucose, "out1", dNCoSubstrate, "in1");
        addCoupling(dNProduct, "out1", dNCoSubstrate, "in2");
        addCoupling(dNCoSubstrate,"out1", this,"out1");
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(515, 271);
        if((ViewableComponent)withName("Glucose")!=null)
             ((ViewableComponent)withName("Glucose")).setPreferredLocation(new Point(10, 180));
        if((ViewableComponent)withName("Product")!=null)
             ((ViewableComponent)withName("Product")).setPreferredLocation(new Point(9, 46));
        if((ViewableComponent)withName("CoSubstrate")!=null)
             ((ViewableComponent)withName("CoSubstrate")).setPreferredLocation(new Point(212, 110));
    }
}
