package DEVSGlycolysis.coupled;

import DEVSGlycolysis.atomic.CoSubstrate;
import DEVSGlycolysis.atomic.Glucose;
import DEVSGlycolysis.atomic.ProductReusable;
import simView.ViewableAtomic;
import simView.ViewableComponent;
import simView.ViewableDigraph;

import java.awt.*;

/**
 * Created with IntelliJ IDEA.
 * User: nick
 * Date: 4/17/14
 * Time: 10:56 AM
 * To change this template use File | Settings | File Templates.
 */
public class Substrate extends ViewableDigraph {

    public static final String inPort1 = "in1";
    public static final String inPort2 = "in2";
    public static final String outPort = "out1";
    public Substrate() {
        this("Substrate");
    }

    public Substrate(String nm) {
        super(nm);
        DNSubstrateConstructor();
    }

    public void DNSubstrateConstructor() {
        this.addOutport("out1");
        this.addInport(inPort1);
        this.addInport(inPort2);

        ViewableAtomic dNProduct = new ProductReusable("ProductReusable", 7);
        ViewableAtomic dNGlucose = new Glucose("Glucose");
        ViewableAtomic dNCoSubstrate = new CoSubstrate("CoSubstrate");

        add(dNProduct);
        add(dNGlucose);
        add(dNCoSubstrate);

        addCoupling(this, inPort1, dNProduct, ProductReusable.inPort);
        addCoupling(this, inPort2, dNGlucose, "in1");
        addCoupling(dNGlucose, "out1", dNCoSubstrate, "in1");
        addCoupling(dNProduct, ProductReusable.outPort, dNCoSubstrate, "in2");
        addCoupling(dNCoSubstrate,"out1", this, outPort);
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(515, 284);
        if((ViewableComponent)withName("CoSubstrate")!=null)
             ((ViewableComponent)withName("CoSubstrate")).setPreferredLocation(new Point(212, 110));
        if((ViewableComponent)withName("ProductReusable")!=null)
             ((ViewableComponent)withName("ProductReusable")).setPreferredLocation(new Point(-4, 43));
        if((ViewableComponent)withName("Glucose")!=null)
             ((ViewableComponent)withName("Glucose")).setPreferredLocation(new Point(6, 180));
    }
}
